//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Client
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Client()
        {
            this.MonthlyPayments = new HashSet<MonthlyPayment>();
        }
    
        public string Plate { get; set; }
        public string Document { get; set; }
        public int DocTypeID { get; set; }
        public string Name { get; set; }
        public string CelPhone { get; set; }
        public Nullable<bool> IsActive { get; set; }
    
        public virtual DocType DocType { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<MonthlyPayment> MonthlyPayments { get; set; }
    }
}
