//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Repositories
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class PLTOEntities : DbContext
    {
        public PLTOEntities()
            : base("name=PLTOEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Configuration> Configurations { get; set; }
        public virtual DbSet<DocType> DocTypes { get; set; }
        public virtual DbSet<Forms> Forms1 { get; set; }
        public virtual DbSet<Rol> Rols { get; set; }
        public virtual DbSet<RolForm> RolForms { get; set; }
        public virtual DbSet<Client> Clients { get; set; }
        public virtual DbSet<Registry> Registries { get; set; }
        public virtual DbSet<MonthlyPayment> MonthlyPayments { get; set; }
        public virtual DbSet<PaymentMethod> PaymentMethods { get; set; }
        public virtual DbSet<AppUser> AppUsers { get; set; }
    
        public virtual ObjectResult<usp_SelectRolAccessData_Result> usp_SelectRolAccessData(Nullable<int> rolId)
        {
            var rolIdParameter = rolId.HasValue ?
                new ObjectParameter("RolId", rolId) :
                new ObjectParameter("RolId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectRolAccessData_Result>("usp_SelectRolAccessData", rolIdParameter);
        }
    
        public virtual ObjectResult<usp_SelectCloseWorkSfhitDates_Result> usp_SelectCloseWorkSfhitDates(Nullable<int> userId)
        {
            var userIdParameter = userId.HasValue ?
                new ObjectParameter("UserId", userId) :
                new ObjectParameter("UserId", typeof(int));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<usp_SelectCloseWorkSfhitDates_Result>("usp_SelectCloseWorkSfhitDates", userIdParameter);
        }
    }
}
