//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyPayment
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MonthlyPayment()
        {
            this.Registries = new HashSet<Registry>();
        }
    
        public string MonthlyPaymentID { get; set; }
        public string Plate { get; set; }
        public string Document { get; set; }
        public int DocTypeID { get; set; }
        public decimal TotalPayment { get; set; }
        public decimal PaidValue { get; set; }
        public decimal Refund { get; set; }
        public System.DateTime PaymentDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Client Client { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Registry> Registries { get; set; }
    }
}
