//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class MonthlyPayment
    {
        public string MonthlyPaymentID { get; set; }
        public string Plate { get; set; }
        public decimal TotalPayment { get; set; }
        public decimal PaidValue { get; set; }
        public decimal Refund { get; set; }
        public System.DateTime StartDate { get; set; }
        public System.DateTime ExpirationDate { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<bool> IsWorkShiftClosed { get; set; }
        public Nullable<System.DateTime> WorkShiftCloseDate { get; set; }
        public Nullable<int> PaymentMethodID { get; set; }
        public Nullable<System.DateTime> PaymentDate { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual Client Client { get; set; }
    }
}
