//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class ReceiptNo
    {
        public int ReceiptID { get; set; }
        public string TableName { get; set; }
        public int TableID { get; set; }
    
        public virtual MonthlyPayment MonthlyPayment { get; set; }
        public virtual Registry Registry { get; set; }
    }
}
