//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class Registry
    {
        public string RegistryID { get; set; }
        public string Plate { get; set; }
        public System.DateTime EntryDate { get; set; }
        public Nullable<System.DateTime> ExitDate { get; set; }
        public Nullable<int> Days { get; set; }
        public Nullable<int> Hours { get; set; }
        public Nullable<int> Minutes { get; set; }
        public Nullable<decimal> TotalPayment { get; set; }
        public Nullable<decimal> Payment { get; set; }
        public Nullable<decimal> Refund { get; set; }
        public Nullable<int> CreatedBy { get; set; }
        public Nullable<int> ModifiedBy { get; set; }
        public Nullable<System.DateTime> ModifiedDate { get; set; }
        public Nullable<bool> IsWorkShiftClosed { get; set; }
        public Nullable<System.DateTime> WorkShiftCloseDate { get; set; }
        public Nullable<int> Locker { get; set; }
        public Nullable<bool> DayPayment { get; set; }
        public Nullable<bool> IsInSite { get; set; }
        public Nullable<int> DeletedBy { get; set; }
        public Nullable<System.DateTime> DeletedDate { get; set; }
    
        public virtual AppUser AppUser { get; set; }
        public virtual AppUser AppUser1 { get; set; }
    }
}
