//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolForm
    {
        public int RolFormID { get; set; }
        public int RolID { get; set; }
        public int FormID { get; set; }
    
        public virtual Forms Form { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
