//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Parking.Repositories
{
    using System;
    using System.Collections.Generic;
    
    public partial class RolForm
    {
        public int RolFormID { get; set; }
        public int RolID { get; set; }
        public int FormID { get; set; }
    
        public virtual Forms Form { get; set; }
        public virtual Rol Rol { get; set; }
    }
}
